---

- hosts: reverse_proxies
  become: true
  vars_files:
    - vault/secrets.yml
  roles:
    - { role: common, tags: ["common"] }
    - { role: create_admin_users, tags: ["admin_users", "users"] }
    - { role: setup_nginx, tags: ["nginx", "reverse-proxy"] }

