all:
  children:
    dbservers:
      hosts: {}
    reverse_proxies:
      hosts: {}
    homelab_services:
      hosts:
        srv50:
          ansible_host: srv50.home.arpa
          host_aliases:
            - alloy.home.arpa
            - git.home.arpa
            - grafana.home.arpa
            - loki.home.arpa
            - prometheus.home.arpa
            - services.home.arpa
            - uptime.home.arpa
    webservers:
      hosts:
        srv11:
          ansible_host: srv11.home.arpa
          host_aliases:
            - ryanjh.home.arpa
        srv30:
          ansible_host: srv30.home.arpa

